// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


// Nav
export const SET_PAGE = 'SET_PAGE';
export const TOGGLE_USER_MODAL = 'TOGGLE_USER_MODAL';
export const TOGGLE_PROFILE_MODAL = 'TOGGLE_PROFILE_MODAL';
export const TOGGLE_AUTH_MODAL = 'TOGGLE_AUTH_MODAL';
export const SET_PROFILE_MODAL = 'SET_PROFILE_MODAL';
export const TOGGLE_POST_MODAL = 'TOGGLE_POST_MODAL';
export const SET_POST_MODAL = 'SET_POST_MODAL';
export const TOGGLE_COMMENT_MODAL = 'TOGGLE_COMMENT_MODAL';
export const SET_COMMENT_MODAL = 'SET_COMMENT_MODAL';
export const TOGGLE_SHARE_MODAL = 'TOGGLE_SHARE_MODAL';
export const SET_MAIN_NAV = 'SET_MAIN_NAV';
export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV';

// Posts
export const GET_POSTS = 'GET_POSTS';
export const SET_POSTS = 'SET_POSTS';
export const GET_POST = 'GET_POST';
export const UPDATE_POST_LIKES = 'UPDATE_POST_LIKES';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const GET_COMMENTS = 'GET_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const POSTS_LOADING = 'POSTS_LOADING';
export const CLEAR_POSTS = 'CLEAR_POSTS';
export const CLEAR_POST = 'CLEAR_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_EDITOR_TEXT = 'UPDATE_EDITOR_TEXT';
export const CLEAR_EDITOR_TEXT = 'CLEAR_EDITOR_TEXT';
export const UPDATE_EDITOR_CATEGORY = 'UPDATE_EDITOR_CATEGORY';
export const CLEAR_EDITOR_CATEGORY = 'CLEAR_EDITOR_CATEGORY';
export const UPDATE_EDITOR_FILES = 'UPDATE_EDITOR_FILES';
export const REMOVE_EDITOR_FILE = 'REMOVE_EDITOR_FILE';
export const CLEAR_EDITOR_FILES = 'CLEAR_EDITOR_FILES';
export const UPDATE_URLS = 'UPDATE_URLS';
export const REMOVE_URL = 'REMOVE_URL';
export const CLEAR_URLS = 'CLEAR_URLS';